[package]

name = "petgraph"
version = "0.4.13"
license = "MIT/Apache-2.0"
authors = [
"bluss",
"mitchmindtree",
]

description = "Graph data structure library. Provides graph types and graph algorithms."
documentation = "https://docs.rs/petgraph/"
repository = "https://github.com/bluss/petgraph"

keywords = ["data-structure", "graph", "unionfind", "graph-algorithms"]
categories = ["data-structures"]

[lib]

name = "petgraph"
bench = false

[profile.release]

[profile.bench]
debug = true

[dependencies]
fixedbitset = { version = "0.1.4" }
quickcheck = { optional = true, version = "0.7.1", default-features = false }
indexmap = { version = "1.0.2", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
rand = { version = "0.5.5", optional = true }

[dev-dependencies]
rand = "0.5.5"
odds = { version = "0.2.19" }
defmac = "0.1"
itertools = { version = "0.7.0", default-features = false }

[features]
default = ["graphmap", "stable_graph"]
graphmap = ["indexmap"]
serde-1 = ["serde", "serde_derive", "indexmap/serde-1"]
stable_graph = []
check = ["quickcheck", "rand"]

# For unstable features
generate = []
unstable = ["generate"]

# feature flags for testing use only
all = ["unstable", "check", "stable_graph", "graphmap"]

[workspace]
members = ["serialization-tests"]

[package.metadata.docs.rs]
features = ["serde-1", "quickcheck"]

[package.metadata.release]
no-dev-version = true
